In [1]:
import torch
print(torch.__version__)
print("GPU available:" , torch.cuda.is_available())
x = torch.rand(5, 3)
print(x)


2.8.0+cu128
GPU available: True
tensor([[0.9738, 0.8119, 0.7774],
        [0.9818, 0.6808, 0.1682],
        [0.9782, 0.2917, 0.3640],
        [0.2462, 0.8868, 0.0604],
        [0.4022, 0.3493, 0.2439]])


In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.8.0+cu128
True


In [2]:
import torch

# 1Dテンソル（ベクトル）
x = torch.tensor([1, 2, 3])
print("x:", x)

# 2Dテンソル（行列）
y = torch.tensor([[1, 2], [3, 4]])
print("y:\n", y)

# 要素ごとの加算
print("x + 10 =", x + 10)

# 行列の掛け算
result = torch.matmul(y, y)
print("y × y =\n", result)


x: tensor([1, 2, 3])
y:
 tensor([[1, 2],
        [3, 4]])
x + 10 = tensor([11, 12, 13])
y × y =
 tensor([[ 7, 10],
        [15, 22]])


In [2]:
import torch

# 1Dテンソル（ベクトル）
x = torch.tensor([1, 2, 3])
print("x:", x)

# 2Dテンソル（行列）
y = torch.tensor([[1, 2], [3, 4]])
print("y:\n", y)

# 要素ごとの加算
print("x + 10 =", x + 10)

# 行列の掛け算
result = torch.matmul(y, y)
print("y × y =\n", result)


x: tensor([1, 2, 3])
y:
 tensor([[1, 2],
        [3, 4]])
x + 10 = tensor([11, 12, 13])
y × y =
 tensor([[ 7, 10],
        [15, 22]])


In [3]:
print("y の形:", y.shape)
print("y の型:", y.dtype)
print("y を NumPy 配列に変換:", y.numpy())


y の形: torch.Size([2, 2])
y の型: torch.int64
y を NumPy 配列に変換: [[1 2]
 [3 4]]


In [4]:
# GPUを使って計算してみる
if torch.cuda.is_available():
    device = torch.device("cuda")
    x_gpu = x.to(device)
    print("GPU上のテンソル：", x_gpu)

GPU上のテンソル： tensor([1, 2, 3], device='cuda:0')
